fix:fix server address error when running in k8s
qiniu/goc pull request #286
Opened 2022-06-30 02:02 UTC by golangaccount

when goc server running  in k8s
client register uri while be transform to is proxy address
in fact,there is no need to transform

add address uri check,make sure address parm is a complete uri

2022-07-07 02:11 UTC, golangaccount commented
/assign @carlji

2022-07-11 02:17 UTC, CarlJi commented
@golangaccount Thanks for your contribution.

The reason of this transform is try to find the proper IP especially in the local multi-interfaces scenario. And yes it's not elegant for the kubernetes scenario. To enhance it, we have solved this drawback in the goc v2 version by using web-socket protocol and welcome to have a try. https://github.com/qiniu/goc/tree/v2

For your PR, i am thinking that it's better to provide a switch in `goc server` to let user choose whether to do this transform or not than changing old behavior. since the default behavior should be compatibility with previous versions。

2022-07-11 02:53 UTC, golangaccount commented
cureent, i use goc v1.x in project,so i think has necessary to merge v1.x.   yea,use this code,the nat network will not work well,i will add a parm in goc server to switch two conditions

2022-07-15 05:34 UTC, golangaccount commented
@CarlJi  i edit the code，add a parm to control the network，if not set，it runing default

2022-07-15 09:59 UTC, CarlJi commented on pkg/cover/server.go
> +	NetworkType     string //solve different network type(1.regist client can direct access ,2.regist client under a proxy network or nat network、same network ect)
The concept  of `NetworkType` seems too  big, actually the goal here is only to check whether to do ip revise during registering。so i prefer:
```go
type server struct{
   ...
   IPRevise bool // whether to do ip revise during registering
```

2022-07-15 10:06 UTC, CarlJi commented on pkg/cover/server.go
> +		realIP := c.ClientIP()
I am thinking that no need to change the `register api`, we can just use `goc sever` to control this behave. like, Launch go server with `goc server --ip_revise=false`
And change here's logic as
```go 
	// only do ip revise as needed.
	if s.IPRevise {
		realIP := c.ClientIP()
		// only for IPV4
		// refer: https://github.com/qiniu/goc/issues/177
		if net.ParseIP(realIP).To4() != nil && host != realIP {
			log.Printf("the registered host %s of service %s is different with the real one %s, here we choose the real one", service.Name, host, realIP)
			service.Address = fmt.Sprintf("http://%s:%s", realIP, port)
		}
	}
```

2022-07-15 10:10 UTC, CarlJi requested changes

2022-07-15 10:10 UTC, CarlJi commented on pkg/cover/server.go
> +	NetworkType     string //solve different network type(1.regist client can direct access ,2.regist client under a proxy network or nat network、same network ect)
`IPRevise` can be passed when goc server lauching like `goc server --ip_revise=false`.
Offically by default, `IPRevise` should be true to keep consistent with previous versions.

2022-07-15 10:17 UTC, CarlJi commented
Hi @golangaccount , if i understood your scenario correctly, switch off the ip revise during registering should meet your requirements。 so no need to change the logic of 'registry API', since it will affect the old behaviors。

2022-07-15 10:19 UTC, CarlJi commented on pkg/cover/server.go
> +	if u.Scheme != "https" && u.Scheme != "http" {
why do we need this check？

2022-07-18 05:33 UTC, golangaccount commented
@CarlJi use bool can solve my problem，but there also has some question. if goc server is running, some client already regist,now i want to regist a new client with no revise,so i must set the value, use bool canot make sure the value is user set.

2022-07-18 06:31 UTC, CarlJi commented
while, if we want to let user be able to control this ability during registering from client side, i actually expect a new PR since it will also need to be changed for the `goc build/install` logic.

for your questions, i suggest to deploy multi goc servers. In my original design concepts, goc server should be lightweight and close to the services under tests。(PS: maybe it should be called `goc proxy` ... )  :sweat_smile:

2022-07-19 07:08 UTC, golangaccount commented
@CarlJi i change the parm,use ip_revise in goc server. i still retain request parm (iprevise) to change the server running style

2022-07-20 09:33 UTC, CarlJi commented
Hi @golangaccount , i am curious do you just use `goc server` alone？and how do you do instrumentation for your services without `goc build/install` ?

2022-07-20 12:52 UTC, golangaccount commented
@CarlJi  i also use goc build/install,  goc server --ip_revise=false can solve my k8s question(other code no need change). 

> when goc server running in k8s client register uri while be transform to is proxy address in fact,there is no need to transform
> 
> add address uri check,make sure address parm is a complete uri

2022-07-21 05:59 UTC, CarlJi commented
/lgtm
/approve

2022-07-21 06:01 UTC, merged